### ISSUE TITLE
[Bug]: LogiOptionsPlus-Install checkver regex can't catch v1.46

### ISSUE THREAD

**Issue by sqliuchang** [danielpauldd/scoop-bucket#1]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

LogiOptionsPlus-Install

### Expected/Current Behaviour

`<a href="#latest" target="_self" rel="undefined">1.46</a>`
Version 1.46 has an additional attribute "rel", therefore the regex expression `"regex": "target=\"_self\">([\\d.]+)"` can't catch it.

### Steps to Reproduce

```console
scoop install LogiOptionsPlus-Install
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'LogiOptionsPlus-Install' (1.44) [64bit] from dpa bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 538764|OK  |   7.0MiB/s|C:/Users/sqliuchang/scoop/cache/LogiOptionsPlus-Install#1.44#https_download01.logi.com_web_ftp_pub_techsupport_optionsplus_logioptionsplus_installer.exe_setup.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of logioptionsplus_installer.exe ... ERROR Hash check failed!
App:         dpa/LogiOptionsPlus-Install
URL:         https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.exe#/setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    f8dc756eb2b766f354d5143bc122fe3a24162feb444f04b2f5142ab2ecab6e50
Actual:      d12a5c75119040d204753e6a549821a823ba239dcf917273e460ed545134875e

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/danielpauldd/scoop-bucket/issues/new?title=LogiOptionsPlus-Install%401.44%3a+hash+check+failed
```

### Possible Solution

Maybe `"regex": "target=\"_self\"[^>]*>([\\d.]+)"` should be better.

### Scoop and Buckets Version

```console
*
```

### Scoop Config

```console
*
```

### PowerShell Version

```console
*
```

**Comment by sqliuchang** [comment]
[https://support.logi.com/api/v2/help_center/en-us/articles.json?label_names=webcontent=productdownload,webproduct=8e72fd48-b41b-11ec-a7c1-5d4cabdc9b43&per_page=1](https://support.logi.com/api/v2/help_center/en-us/articles.json?label_names=webcontent=productdownload,webproduct=8e72fd48-b41b-11ec-a7c1-5d4cabdc9b43&per_page=1)
or
[https://support.logi.com/hc/en-us/articles/15800857352215-Logi-Options-](https://support.logi.com/hc/en-us/articles/15800857352215-Logi-Options-)
always return an accurate version number.

**Comment by danielpauldd** [comment]
Thanks for the bug report, but I'm not going to fix that, as I'm not usings Logi Options anymore.
